config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name, namespace_name=nil)
    instance_eval(File.read(Rails.root.join("config/routes", namespace_name.to_s, "#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  draw :admin
  draw :api
  root 'fx/home#index'
  #get 'auth' => 'fx/home#index'
  match 'auth', to: 'fx/home#index', via: [:get, :post]
  get "login" => "core/sessions#new", :as => :login
  get "invite/:id" => "users#invite"
  get 'logout' => "core/sessions#logout", :as => :logout
  get '/docs/index', to: 'docs#index'
  get "fx/signup" => "fx/users#new", :as => :signup
  get 'qrcode/:id' => 'fx/home#qrcode'
  namespace :core do
    resources :sessions, :only => [:new, :create] do
      collection do
        get :forget_password, :get_sms, :success, :show_reset_password, :logout
        post :reset_password, :validate_account, :validate_code, :captcha_login
      end
    end
  end
  namespace :fx do
    resources :users do
      collection do
        get :register,:apply
        post :validate_code,:validate_params,:send_sms
      end
    end
  
    resources :home, :only=>[:index] do
      collection do 
        get :activate,:return_amount ,:tax_rates,:apply,:reback,:note,:verify
      end
    end
    
    resources :withdraws, :only=>[:index,:new,:create] do
       
    end
    
    
    get "download"=>"home#download"
 
  end
end

app/models/fx/auction.rb
class Fx::Info < ActiveRecord::Base
  self.table_name = "fx_infos"
end

app/models/fx/auction_record.rb
class Fx::AuctionRecord < ActiveRecord::Base
  self.table_name = "fx_auction_records"
end

app/models/fx/employee.rb
class Fx::Employee < ActiveRecord::Base
  self.table_name = "fx_employees"
  belongs_to :user,foreign_key: "id"
  ROLE_PERCENT    ={
      0 => 2,
      1 => 2,
      2 => 3,
      3 => 5,
      4 => 5,
      5 => 5
  }
  ROLE_NAME       ={
      0 => "助理",
      1 => "经理",
      2 => "总监",
      3 => "部长",
      4 => "总经理",
      5 => "总经理以上"
  }

  def self.role_name_percent
    hash={}
    ROLE_NAME.each{|k,v| hash[k]="#{v}#{ROLE_PERCENT[k]}%"}
    hash
  end

  def role_name
    ROLE_NAME[role]
  end

  def percent
    ROLE_PERCENT[role]
  end

  def percent_display
      "#{percent}%"
  end

end

app/models/fx/info.rb
class Fx::Info < ActiveRecord::Base
  self.table_name = "fx_infos"
end

app/models/fx/invite.rb
class Fx::Invite < ActiveRecord::Base
  self.table_name = "fx_invites"
  #邀请表
  belongs_to :user
  belongs_to :used_byer,foreign_key: "used_by",class_name: "Fx::User"

end

app/models/fx/level.rb
class Fx::Level < ActiveRecord::Base
  self.table_name = "fx_levels"
  has_one :upgrade
  scope :active, -> { where :active => true }
  LEVEL=
      {1 => "普通合伙人",
       2 => "高级合伙人",
       3 => "事业合伙人"
      }

  after_create do
    self.build_upgrade.save!
  end

  def dealer1_percent_name
    "#{dealer1_percent}%"
  end

  def dealer2_percent_name
    "#{dealer2_percent}%"
  end

  def dealer3_percent_name
    "#{dealer3_percent}%"
  end

end

app/models/fx/relation.rb
class Fx::Relation < ActiveRecord::Base
  self.table_name = "fx_relations"
  # acts_as_nested_set parent_column: "user_id",primary_column: "dealer_id",depth_column: "dealer_level",counter_cache: "dealers_count"

  belongs_to :user
  belongs_to :dealer, foreign_key: "dealer_id", class_name: "::Fx::User"
  scope :recent, -> { order('created_at DESC') }

 
  
  self.json_options={
    :only    => ["user_id"],
    :include => {
      dealer: {:only => [:total_amount], methods: [:name,:level_name,:info_dealer1_count]} 
    }
  }
end

app/models/fx/setting.rb
class Fx::Setting < ActiveRecord::Base
  self.table_name = "fx_settings"
  serialize :value
  # serialize :apply
  # serialize :poster
end

app/models/fx/tax_rate.rb
class Fx::TaxRate < ActiveRecord::Base
  self.table_name = "fx_tax_rates"
  belongs_to :user
  belongs_to :trade
  scope :recent, -> { order('created_at DESC') }
  STATE={
      0 => "未结算",
      1 => "已结算"
  }

  def trade_number
    "PXF#{self.id}#{Time.now.to_i}"
  end

  def pay
    Fx::Transation.create!(user_id: self.user_id, amount: self.amount, sort: 0, subject: "个人所得税")
  end

  def state_name
    STATE[self.state]
  end

  def pay!
    pay
    user.outcome!(self.amount)
  end

  def balance_income
    state==1 ? total_amount-amount :  0
  end

  self.json_options={
      :only    => ["amount", "total_amount", "date", "state"],
      :methods => [:month_amount]
  }
end

app/models/fx/trade.rb
class Fx::Trade < ActiveRecord::Base
  self.table_name = "fx_trades"
  has_many :transations
  belongs_to :user
  scope :active, -> { where :active => true }
  scope :recent, -> { order('created_at DESC') }


  OPTYPE_NAME={
    1 => "在线招标",
    2 => "商城",
    3 => "脉脉圈",
    4 => "所得税",
    5 => "培训费"
  }

  after_create do
    pay!
  end

  def optype_name
    OPTYPE_NAME[optype]
  end

  #分配分销获利todo移除实时余额获利
  def pay!
    #个人订单消费累计
    user.update!(cost_amount: user.cost_amount+amount)
    #分给自己
    if state == -1
      sort = -1
    else
      sort = 1
    end
    self.transations.create!(user_id: user.id, amount: amount,sort: sort,subject: "个人消费返利")
    user.info.update!({amount: user.info.amount + amount})
    user.update!(total_amount: user.total_amount + amount)
    # #二级分销利润分配
    if prev_dealer=user.prev_dealer
      dealer1_percent=employee_percent(prev_dealer, prev_dealer.level.send(:dealer1_percent))
      dealer1_amount =amount*dealer1_percent
      self.transations.create!(user_id: prev_dealer.id, amount: dealer1_amount, dealer_level: 1, sort: sort,subject: "一级分销返利")
      prev_dealer.info.update!({amount1: prev_dealer.info.amount1+dealer1_amount})
      prev_dealer.update!({total_amount: prev_dealer.total_amount + dealer1_amount})
      # prev_dealer.income!(dealer1_amount)
      if prev2_dealer=prev_dealer.prev_dealer
        dealer2_percent=employee_percent(prev2_dealer, prev2_dealer.level.send(:dealer2_percent))
        dealer2_amount =amount*dealer2_percent
        self.transations.create!(user_id: prev2_dealer.id, amount: dealer2_amount, dealer_level: 2, sort: sort,subject: "二级分销返利")
        prev2_dealer.info.update!({amount2: prev2_dealer.info.amount2.to_f + dealer2_amount})
        prev2_dealer.update!({total_amount: prev2_dealer.total_amount + dealer2_amount})
        # prev2_dealer.income!(dealer2_amount)
        #        if prev3_dealer=prev2_dealer.prev_dealer
        #          dealer3_percent=employee_percent(prev3_dealer,prev3_dealer.level.send(:dealer3_percent))
        #          dealer3_amount =amount*dealer3_percent
        #          self.transations.create!(user_id: prev3_dealer.id, amount: dealer3_amount, dealer_level: 3, sort: 1)
        #          prev3_dealer.info.update!({amount3: user.info.amount3+dealer3_amount})
        #          # prev3_dealer.income!(dealer3_amount)
        #        end
      end
    end
  end

  #内部员工新增获利
  def employee_percent(dealer, percent)
    if employee=dealer.is_employee
      percent+=employee.percent
    end
    percent/100.00
  end


end

app/models/fx/upgrade.rb
class Fx::Upgrade < ActiveRecord::Base
  self.table_name = "fx_upgrades"
  belongs_to :level
end

app/controllers/admin/fx/application_controller.rb
class Admin::Fx::ApplicationController <  Admin::ApplicationController

end

app/controllers/admin/fx/employees_controller.rb
class Admin::Fx::EmployeesController < Admin::Fx::ApplicationController
  before_action :current_tab

  def index
    @employees = ::Fx::Employee._where(params[:where])._order(params[:order]).page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @employees }
    end
  end

  def show
    @employee = ::Fx::Employee.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @employee }
    end
  end

  def new
    @employee = ::Fx::Employee.new

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @employee }
    end
  end

  def create
     success= ::Fx::Employee.create(employee_params)

    respond_to do |format|
      if success
        flash[:notice] = '等级创建成功'
        format.html { redirect_to :back}
        format.xml { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @employee = ::Fx::Employee.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @employee }
    end
  end

  def update
    @employee = ::Fx::Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(employee_params)
        flash[:notice] = '等级更新成功'
        format.html { redirect_to :back }
        format.js { head :ok }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { raise }
        format.xml { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  def delete
    @employee = ::Fx::Employee.find(params[:id])

    respond_to do |format|
      format.html { render template: 'admin/shared/delete', locals: {record: @employee, unable_msg: '此等级无法删除？'}, :layout => false }
      format.xml { render :xml => @employee }
    end
  end

  def destroy
    @employee = ::Fx::Employee.find(params[:id])
    @employee.destroy_softly

    respond_to do |format|
      format.html { redirect_to :back, :status => :ok }
      format.xml { head :ok }
    end
  end

  protected

  def current_tab
    @current_tab="employee"
  end

  def employee_params
    params[:employee].permit([:id,:name,:role])
  end

  def authorized?
    true
  end
end

app/controllers/admin/fx/invites_controller.rb
class Admin::Fx::InvitesController < Admin::Fx::ApplicationController
  before_action :current_tab
  def index
    @invites = ::Fx::Invite._where(params[:where])._order(params[:order]).page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @invites }
    end
  end

  def show
    @invite = ::Fx::Invite.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @invite }
    end
  end

  def new
    @invite = ::Fx::Invite.new

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @invite }
    end
  end

  def create
    @invite = ::Fx::Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        flash[:notice] = '等级创建成功'
        format.html { redirect_to :back }
        format.xml { render :xml => @invite, :status => :created, :location => @invite }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @invite.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @invite = ::Fx::Invite.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @invite }
    end
  end

  def update
    @invite = ::Fx::Invite.find(params[:id])

    respond_to do |format|
      if @invite.update_attributes(invite_params)
        flash[:notice] = '等级更新成功'
        format.html { redirect_to :back }
        format.js { head :ok }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { raise }
        format.xml { render :xml => @invite.errors, :status => :unprocessable_entity }
      end
    end
  end

  def delete
    @invite = ::Fx::Invite.find(params[:id])

    respond_to do |format|
      format.html { render template: 'admin/shared/delete', locals: {record: @invite, unable_msg: '此等级无法删除？'}, :layout => false }
      format.xml { render :xml => @invite }
    end
  end

  def destroy
    @invite = ::Fx::Invite.find(params[:id])
    @invite.destroy_softly

    respond_to do |format|
      format.html { redirect_to :back, :status => :ok }
      format.xml { head :ok }
    end
  end

  protected
  def current_tab
    @current_tab="invite"
  end

  def invite_params
    params[:invite].permit([:name,:label, :dealer1_percent, :dealer2_percent, :dealer3_percent])
  end

  def authorized?
    true
  end
end

app/controllers/admin/fx/levels_controller.rb
class Admin::Fx::LevelsController < Admin::Fx::ApplicationController
  before_action :current_tab

  def index
    @levels = ::Fx::Level.active._where(params[:where])._order(params[:order]).page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @levels }
    end
  end

  def show
    @level = ::Fx::Level.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @level }
    end
  end

  def new
    @level = ::Fx::Level.new

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @level }
    end
  end

  def create
    @level = ::Fx::Level.new(level_params)

    respond_to do |format|
      if @level.save
        flash[:notice] = '等级创建成功'
        format.html { redirect_to :back}
        format.xml { render :xml => @level, :status => :created, :location => @level }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @level.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @level = ::Fx::Level.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @level }
    end
  end

  def update
    @level = ::Fx::Level.find(params[:id])

    respond_to do |format|
      if @level.update_attributes(level_params)
        flash[:notice] = '等级更新成功'
        format.html { redirect_to :back }
        format.js { head :ok }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { raise }
        format.xml { render :xml => @level.errors, :status => :unprocessable_entity }
      end
    end
  end

  def delete
    @level = ::Fx::Level.find(params[:id])

    respond_to do |format|
      format.html { render template: 'admin/shared/delete', locals: {record: @level, unable_msg: '此等级无法删除？'}, :layout => false }
      format.xml { render :xml => @level }
    end
  end

  def destroy
    @level = ::Fx::Level.find(params[:id])
    @level.destroy_softly

    respond_to do |format|
      format.html { redirect_to :back, :status => :ok }
      format.xml { head :ok }
    end
  end

  protected

  def current_tab
    @current_tab="level"
  end

  def level_params
    params[:level].permit([:name,:label, :dealer1_percent, :dealer2_percent, :dealer3_percent])
  end

  def authorized?
    true
  end
end

app/controllers/admin/fx/settings_controller.rb
class Admin::Fx::SettingsController < Admin::Fx::ApplicationController
  before_action :current_tab

  def index
    @setting = ::Fx::Setting.where(key: "apply").first_or_create do |s|
      s.value={limit: 10000,remin: 10000}
    end
    @train_fee_setting = ::Fx::Setting.where(key: "train_fee").first_or_create do |s|
      s.value=1
    end
    @audit_setting = ::Fx::Setting.where(key: "audit_type").first_or_create do |s|
      s.value=1
    end
    @audit_cost_setting = ::Fx::Setting.where(key: "audit_cost_amount").first_or_create do |s|
      s.value=100
    end
    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @levels }
    end
  end

  def update
    params[:setting].each do |key, value|
      setting =Fx::Setting.where(key: key).first
      setting.update_attributes(:value => value)
    end
    respond_to do |format|
      flash[:notice] = '等级更新成功'
      format.html { redirect_to :back }
      format.js { head :ok }
      format.xml { head :ok }
    end
  end

  def ui
    @setting = ::Fx::Setting.where(key: "poster").first_or_create do |s|
      s.value=[]
    end
    @posters =@setting.value
    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @levels }
    end
  end

  protected

  def current_tab
    @current_tab="setting"
  end

  def setting_params
    params[:setting].permit([apply: [:limit, :remain, :tax_rate]], poster: [:pic, :url])
  end

  def authorized?
    true
  end
end

app/controllers/admin/fx/tax_rates_controller.rb
class Admin::Fx::TaxRatesController < Admin::Fx::ApplicationController
  before_action :current_tab

  def index
    account=params[:where].delete(:account) if !params[:where].blank?
    @tax_rates = Fx::TaxRate._where(params[:where])._order(params[:order])
    if !account.blank?
      ids =Core::User.where("account like ?","%#{account}%").pluck(:id)
      @tax_rates=@tax_rates.joins(:user).where(fx_users: {id: ids})
    end
    @tax_rates =@tax_rates.page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.xml { render :xml => @tax_rates }
    end
  end

  protected

  def current_tab
    @current_tab="tax_rate"
  end

  def authorized?
    true
  end
end

app/views/fx/home/_qrcode_img.html.erb
<style>
    table {
        border-width: 0;
        border-style: none;
        border-color: #0000ff;
        border-collapse: collapse;
    }
    td {
        border-left: solid 4px #000;
        padding: 0; 
        margin: 0; 
        width: 0px; 
        height: 4px; 
    }
    td.black { border-color: #000; }
    td.white { border-color: #fff; }
</style>

<%= raw @qr.as_html %>

app/views/fx/home/_transation_list.html.erb
<%if @transations.present?%>
  <%@transations.each do |obj|%>
    <div class="kind clearfix">
        <div class="kind_brand f_left">
            <span class="brand_name"> 商城订单</span>
            <span class="brand_time"> <%=obj.created_at.strftime("%Y-%m-%d %H:%M:%S")%></span>
        </div>
        <div class="kind_pay f_right">
            <span class="pay_price"><%=format_price(obj.trade.try(:total_amount))%> </span>
            <%if obj.sort == 1%>
              <span class="pay_back"> <%=image_tag("fx/back_red.png")%> <%=format_price(obj.amount)%></span>
            <%else%>
              <span class="pay_fan"><%=image_tag("fx/fan.png")%>  <%=format_price(obj.amount)%></span>
            <%end%>
        </div>
    </div>
  <%end%>
<%end%>

app/views/fx/home/activate.html.erb
<header class="top_bar clearfix">
    <div class="common" style="border:2px solid #C3C3C3">
        <a href="/" class="top_img"><%=image_tag("fx/back.png")%></a>
        <span class="top_size">激活</span>
       <!-- <a href="#" class="top_point f_right"><%=image_tag("fx/dd.png")%></a>-->
    </div>
</header>
<main class= "startcode">
    <div class="main_img">
        <%=image_tag("fx/bg_t.jpg")%>
    </div>
    <div class="content_introduce">
        <h3>如何激活普通合伙人资格？</h3>
        <p>
            恭喜您获得会展邦合伙人资格，下一步您只需要去会展邦商城，购买任何商品，返利金额达到XXX元，
            即可激活资格，成为真正的会展邦普通合伙人，永久享受普通合伙人的权益。
        </p>
    </div>
    <div class="content_introduce">
        <h3>会展邦合伙人有哪些权益？</h3>
        <p> 3、从消费者（省钱）角度，申请成为会展邦合伙人相当于办了一张会展邦商城的VIP卡，
            自己买东西享受6-9折优惠，直接返现，直接省钱。</p>
        <p>
            4、从创业者（挣钱）角度，申请成为会展邦合伙人，相当于免费开了一家超级网上折扣商城，
            作为商城的老板，您不用关心进货，物流，售后等所有劳心的事情，这些事情统统由会展邦搞定，
            您至于要把您的商城分享出去就可以坐收佣金，“平台+个人”是互联网时代创业的最高效的模式。
        </p>
    </div>
    <div class="foot_img"><%=image_tag("fx/bg1.png")%></div>
</main>

app/views/fx/home/apply.html.erb
	
<header class="top_bar clearfix">
    <div class="common" style="border:2px solid #C3C3C3">
        <a href="http://mall.eventnation.com.cn/android" class="top_img">   <%=image_tag("fx/back.png")%> </a>
        <span class="top_size">申请合伙人</span>
        
    </div>
</header>
<main>
    <div class="content_imglogo">
        <%=image_tag("fx/logo.png")%>
 
    </div>
    <div class="content_apply">
        合伙人计划
    </div>
    <div class="content_input">
        <a href="/fx/users/apply" data-remote="true" > <input type="submit" value="申请为合伙人" /></a>
    </div>
    <div class="content_introduce">
        <h3>会展邦合伙人是什么？</h3>
        <p>1、从消费者（省钱）角度，申请成为会展邦合伙人相当于办了一张会展邦商城的VIP卡，
            自己买东西享受6-9折优惠，直接返现，直接省钱。</p>
        <p>
            2、从创业者（挣钱）角度，申请成为会展邦合伙人，相当于免费开了一家超级网上折扣商城，
            作为商城的老板，您不用关心进货，物流，售后等所有劳心的事情，这些事情统统由会展邦搞定，
            您至于要把您的商城分享出去就可以坐收佣金，“平台+个人”是互联网时代创业的最高效的模式。
        </p>
    </div>
</main>

app/views/fx/home/index.html.erb
<header class="top_bar clearfix">
    <div class="common" style="border:2px solid #C3C3C3">
        <a href="http://mall.eventnation.com.cn/customer/account" class="top_img" >
            <!--<a href="http://mall.eventnation.com.cn/android" class="top_img">-->  <%=image_tag("fx/back.png")%> </a>
        <span class="top_size">财富分享</span>

    </div>
</header>
<main>
    <div class="center_lbt swiper-container">
        <div class="lbt swiper-wrapper">
            <%@posters.each do |item|%>
              <div class="swiper-slide">
                  <a href="<%=item[:url]%>"><%=image_tag(get_img_url(item[:pic]))%></a>
              </div>
            <%end%>
        </div>
        <div class="swiper-pagination"></div>
    </div>

    <div class="center_user clearfix">
        <div class="user_img f_left">
            <%=avatar_tag(current_user.avatar_url,:class => 'img-circle')%> 
        </div>
        <div class="user_mas f_left">
            <span class="user_mas_name"><%=current_user.nickname%> <em><%=current_user.province_name%></em></span>
            <span>当前级别：<em> <%=@user.level.try(:name)%></em></span>
        </div>
    </div>
    <div class="center_bb">
        <span class="bb_name">邦邦余额</span>
        <span class="bb_num">
            <em> <%=link_to '<余额明细',fx_withdraws_path%> </em>
            <%=format_price(current_user.bang_amount || 0)%>
            <em> <%=link_to '余额转出>',new_fx_withdraw_path %> </em>
        </span>
    </div>
    <div class="mingci">
        <ul class="mingci_item">
            <li>
                <div class="item_img f_left">
                    <%=image_tag("fx/red_mingci.png")%>
                </div>
                <div class="item_pm f_right">
                    <span>全国排名</span>
                    <em><%=@user.rank%>名</em>
                    <span>与前1名相差</span>
                    <em><%=format_price(@user.distance_amount)%></em>
                </div>
                <div class="clearfix"></div>
            </li>
            <li>
                <div class="item_img f_left">
                    <%=image_tag("fx/blue_mingci.png")%>
                </div>
                <div class="item_sjpm f_right">
                    <span>省级排名</span>
                    <em><%=@user.province_rank%>名</em>
                    <span>与前1名相差</span>
                    <em><%=format_price(@user.distance_province_amount)%></em>
                </div>	
                <div class="clearfix"></div>
            </li>
        </ul>
    </div>
    <div class="rebate">
        <ul>
            <li>
                <a href="/fx/home/return_amount?type=my"> 
                    <span class="rebate_total"></span>
                    <%=image_tag("fx/my.png",:class=>"rebate_img")%> 
                    <span class="rebate_consume">消费返利</span>
                    <span class="rebate_mon" style="color: #FD6363;"><%=format_price(@user.info.try(:amount))%></span>
                </a>
            </li>
            <li> 
                <a href="/fx/home/return_amount?type=partner"> 
                    <span class="rebate_total"><%=image_tag("fx/b_p.png")%>
                        <em style="color: #A4D1FB;">
                            <%=@user.info.try(:dealer1_count)%>
                        </em></span>
                    <%=image_tag("fx/my_2.png", :class=>"rebate_img")%>
                    <span class="rebate_consume">消费返利</span>
                    <span class="rebate_mon" style="color: #A4D1FB;"><%=format_price(@user.info.try(:amount1))%></span>
                </a>
            </li>
            <li>
                <a href="/fx/home/return_amount?type=shoper"> 
                    <span class="rebate_total"><%=image_tag("fx/y_p.png")%><em style="color: #FFE100;"><%=@user.info.try(:dealer2_count)%></em></span>
                    <%=image_tag("fx/my_3.png",:class=>"rebate_img")%>
                    <span class="rebate_consume">消费返利</span>
                    <span class="rebate_mon" style="color: #FFE100;"><%=format_price(@user.info.try(:amount2))%></span>
                </a>
            </li>
            <li>
               <!-- <a href="/fx/home/return_amount?type=all">-->
                    <span class="rebate_total"><%=image_tag("fx/g_p.png")%><em style="color: #7FC469;"><%=@user.info.try(:dealer_count)%></em></span>
                    <%=image_tag("fx/my_4.png" ,:class=>"rebate_img")%> 
                    <span class="rebate_consume">返利总额</span>
                    <span class="rebate_mon" style="color: #7FC469;"><%=format_price(@user.try(:total_amount))%></span>
                </a>
            </li>
            <li>
              <!--  <a href="/fx/home/return_amount?type=moth">-->
                    <span class="rebate_total"></span>
                    <%=image_tag("fx/my_5.png",:class=>"rebate_img")%>
                    <span class="rebate_consume">本月返利</span>
                    <span class="rebate_mon" style="color: #A4D1FB;"><%=format_price(@user.info.try(:current_month_amount))%></span>
                 
            </li>
            <li>
                <a href="/fx/home/tax_rates">
                    <span class="rebate_total"></span>
                    <%=image_tag("fx/my_6.png" ,:class=>"rebate_img")%>
                    <span class="rebate_consume">个人所得税</span>
                    <span class="rebate_mon" style="color: #F7B652;"><%=format_price(@user.tax_amount)%></span>
                </a>
            </li>
            <li>
                <a href="/qrcode/<%=@user.id%>">  
                    <span class="rebate_total"></span>
                    <%=image_tag("fx/my_7.png" ,:class=>"rebate_img")%>
                    <span class="rebate_consume">开始推广</span>
                    <span class="rebate_mon" style="color: #A4D1FB;"></span>
                </a>
            </li>
            <li>
                <a href="/fx/home/note">
                    <span class="rebate_total"></span>
                    <%=image_tag("fx/my_8.jpg" ,:class=>"rebate_img")%>
                    <span class="rebate_consume pink">创业笔记</span>
                    <span class="rebate_mon" style="color: #A4D1FB;"></span>
                </a>
            </li>
        </ul>
    </div>
</main>

<script>
  //轮播图
  var swiper = new Swiper('.swiper-container', {
      pagination: '.swiper-pagination',
      paginationClickable: true,
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: 2500,
      autoplayDisableOnInteraction: false
  });
</script>